//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده با گذر واژه مغایرت دارد!.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل تایید نشده است!.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما نام کاربری را مشخص نکردید!.
        /// </summary>
        public static string ErrorMessage3000 {
            get {
                return ResourceManager.GetString("ErrorMessage3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما رمز عبور را مشخص نکردید!.
        /// </summary>
        public static string ErrorMessage3010 {
            get {
                return ResourceManager.GetString("ErrorMessage3010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه می باشد.
        /// </summary>
        public static string ErrorMessage3020_3030 {
            get {
                return ResourceManager.GetString("ErrorMessage3020_3030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر تأیید نشده است!.
        /// </summary>
        public static string ErrorMessage3040 {
            get {
                return ResourceManager.GetString("ErrorMessage3040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر فعال نیست!.
        /// </summary>
        public static string ErrorMessage3050 {
            get {
                return ResourceManager.GetString("ErrorMessage3050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان انقضا برای این کاربر مشخص نشده است!.
        /// </summary>
        public static string ErrorMessage3060 {
            get {
                return ResourceManager.GetString("ErrorMessage3060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری منقضی شد!.
        /// </summary>
        public static string ErrorMessage3070 {
            get {
                return ResourceManager.GetString("ErrorMessage3070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify user IP!.
        /// </summary>
        public static string ErrorMessage3080 {
            get {
                return ResourceManager.GetString("ErrorMessage3080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما IP کاربر را مشخص نکردید!.
        /// </summary>
        public static string ErrorMessage3090 {
            get {
                return ResourceManager.GetString("ErrorMessage3090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP کاربر تأیید نشده است!.
        /// </summary>
        public static string ErrorMessage3100 {
            get {
                return ResourceManager.GetString("ErrorMessage3100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP کاربر فعال نیست!.
        /// </summary>
        public static string ErrorMessage3110 {
            get {
                return ResourceManager.GetString("ErrorMessage3110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا اطلاعات را مجددا به شکل صحیح وارد نمایید!.
        /// </summary>
        public static string ErrorMessage3120 {
            get {
                return ResourceManager.GetString("ErrorMessage3120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمات عبور مغایرت دارند.
        /// </summary>
        public static string ErrorMessage3130 {
            get {
                return ResourceManager.GetString("ErrorMessage3130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با این ایمیل آدرس وجود دارد.
        /// </summary>
        public static string ErrorMessage3140 {
            get {
                return ResourceManager.GetString("ErrorMessage3140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با این ایمیل آدرس ثبت نشده است!.
        /// </summary>
        public static string ErrorMessage3150 {
            get {
                return ResourceManager.GetString("ErrorMessage3150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور وارد شده صحیح نمی باشد!.
        /// </summary>
        public static string ErrorMessage3160 {
            get {
                return ResourceManager.GetString("ErrorMessage3160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده موجود می باشد.
        /// </summary>
        public static string IsEmailInUse {
            get {
                return ResourceManager.GetString("IsEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی وارد شده موجود می باشد.
        /// </summary>
        public static string IsMainCategoryInUse {
            get {
                return ResourceManager.GetString("IsMainCategoryInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن وارد شده موجود می‌باشد.
        /// </summary>
        public static string IsPhoneNumberInUse {
            get {
                return ResourceManager.GetString("IsPhoneNumberInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربری وارد شده موجود می باشد.
        /// </summary>
        public static string IsUsernameInUse {
            get {
                return ResourceManager.GetString("IsUsernameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر طول {0} باید {1} باشد!.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل طول {0} باید {1} باشد!.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور اشتباه می باشد.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس تایید نشده است!.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الویت می بایست بین {1} تا {2} باشد!.
        /// </summary>
        public static string Prioritize {
            get {
                return ResourceManager.GetString("Prioritize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کالا می بایست بین {2} تا {1} کاراکتر باشد!.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن فیلد  {0} اجباری می باشد!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول این فیلد می بایست بین {2} تا {1} کاراکتر باشد!.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای غیرمنتظره!.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0}  قبلا در ثبت شده است!.
        /// </summary>
        public static string Unique {
            get {
                return ResourceManager.GetString("Unique", resourceCulture);
            }
        }
    }
}
