//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Tables {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Tables.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس درباره ما.
        /// </summary>
        public static string AboutImage {
            get {
                return ResourceManager.GetString("AboutImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن هدف.
        /// </summary>
        public static string GoalDescription {
            get {
                return ResourceManager.GetString("GoalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان هدف.
        /// </summary>
        public static string GoalTitle {
            get {
                return ResourceManager.GetString("GoalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن ماموریت.
        /// </summary>
        public static string MissionDescription {
            get {
                return ResourceManager.GetString("MissionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان ماموریت.
        /// </summary>
        public static string MissionTitle {
            get {
                return ResourceManager.GetString("MissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعار.
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر عنوان.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن درباره ما.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن چشم انداز.
        /// </summary>
        public static string VisionDescription {
            get {
                return ResourceManager.GetString("VisionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان چشم انداز.
        /// </summary>
        public static string VisionTitle {
            get {
                return ResourceManager.GetString("VisionTitle", resourceCulture);
            }
        }
    }
}
